plugins {
    alias(libs.plugins.shadow)
}

sourceCompatibility = 21
targetCompatibility = 21

repositories {
    maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }
}

dependencies {
    compileOnly "org.allaymc.allay:api:0.17.0-SNAPSHOT"

    implementation project(':api')
    implementation project(':common:loader-utils')
}

processResources {
    filesMatching('plugin.json') {
        expand 'pluginVersion': project.ext.fullVersion
    }
}

shadowJar {
    archiveFileName = "LuckPerms-Allay-${project.ext.fullVersion}.jar"

    from {
        project(':allay').tasks.shadowJar.archiveFile
    }
}

artifacts {
    archives shadowJar
}
