plugins {
    alias(libs.plugins.shadow)
    alias(libs.plugins.allaygradle)
}

sourceCompatibility = 21
targetCompatibility = 21

allay {
    api = "0.17.0-SNAPSHOT"

    plugin {
        it.entrance = "me.lucko.luckperms.allay.loader.AllayLoaderPlugin"
        it.name = "LuckPerms"
        it.description = "A permissions plugin."
        it.authors = ["Luck"]
        it.version = project.ext.fullVersion
        it.website = "https://luckperms.net"
    }
}

dependencies {
    implementation project(':api')
    implementation project(':common:loader-utils')
}

shadowJar {
    archiveFileName = "LuckPerms-Allay-${project.ext.fullVersion}.jar"

    from {
        project(':allay').tasks.shadowJar.archiveFile
    }
}

artifacts {
    archives shadowJar
}
